title: 곰탱이의 이것저것
logo_img: /assets/img/icons/BlogLogo.png
favicon: /assets/favicon.ico
description: bear11235's blog
global_tags: jekyll theme simplex golasblog responsive html5
copyright: © bear11235 2023

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
